services:
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: alberto
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: banco
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alberto -d banco"]
      interval: 5s
      timeout: 5s
      retries: 10

  back:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: alberto
      DB_PASSWORD: 12345678
      DB_NAME: banco
    depends_on:
      database:
        condition: service_healthy

  front:
    build: ./frontend
    ports:
      - "5174:5174"
    depends_on:
      - back

volumes:
  db_data:
